// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ1lM8KcmBLhv5ihShvkXT_bQK9-oYOh4',
    appId: '1:462471782086:web:66ca6dc168675d103581c7',
    messagingSenderId: '462471782086',
    projectId: 'fir-firebase-b23e3',
    authDomain: 'fir-firebase-b23e3.firebaseapp.com',
    storageBucket: 'fir-firebase-b23e3.appspot.com',
    measurementId: 'G-CVJ04QFFW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1FTHsXy19hccXbc7rcccScx_r2VQAZQw',
    appId: '1:462471782086:android:100e5464bc16c35b3581c7',
    messagingSenderId: '462471782086',
    projectId: 'fir-firebase-b23e3',
    storageBucket: 'fir-firebase-b23e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1bgs9bT6ZCTER2cUaQLQEzSoav01ECg',
    appId: '1:462471782086:ios:2f42fc22a87554343581c7',
    messagingSenderId: '462471782086',
    projectId: 'fir-firebase-b23e3',
    storageBucket: 'fir-firebase-b23e3.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP1bgs9bT6ZCTER2cUaQLQEzSoav01ECg',
    appId: '1:462471782086:ios:2f42fc22a87554343581c7',
    messagingSenderId: '462471782086',
    projectId: 'fir-firebase-b23e3',
    storageBucket: 'fir-firebase-b23e3.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ1lM8KcmBLhv5ihShvkXT_bQK9-oYOh4',
    appId: '1:462471782086:web:bb01107f059ae4403581c7',
    messagingSenderId: '462471782086',
    projectId: 'fir-firebase-b23e3',
    authDomain: 'fir-firebase-b23e3.firebaseapp.com',
    storageBucket: 'fir-firebase-b23e3.appspot.com',
    measurementId: 'G-W2YQLWM2JC',
  );

}